fix/feat: Updated the package.json again, improved documentation, updated the installer and runner scripts

diff --git a/.docker/qview3d-run b/.docker/qview3d-run
--- a/.docker/qview3d-run
+++ b/.docker/qview3d-run
@@ -6,32 +6,55 @@
 # read is a built-in bash command that reads user input and stores it in the string(s)
 # on the right.
 # -p Causes it to print text before reading user input
-read -p "Would you like to be in development or production mode? (prod/dev) " MODE
+read -p "Would you like to be in development or production mode? (prod/dev/dev-client) " MODE
 
-source server/.python-venv/bin/activate
+source $DOCKER_APP_PATH/server/.python-venv/bin/activate
 
 # Convert all uppercase characters to lower case
 if [ "${MODE@L}" == "dev" ]; then
     echo "Setting up the client and server in development mode"
     
     # Start client
-    cd client
+    cd $DOCKER_APP_PATH/client
     # Automatically rebuilds client when changes are made
-    # Also, stores all the stderr and stdout messages in vite_server.log
-    npx vite build --watch > ../logs/vite_server.log 2>&1 &
-    echo "Wait a little bit for the client to rebuild before opening the webpage. Else you'll get 404s"
+    # Only shows errors, and doesn't minify the code as we would like to be able to read it at this point
+    npx vite build --watch --minify false --logLevel "error" &
+    VITE_SERVER_PID=$!
 
-    sleep 5
+    # Kills the Vite server after the script exits
+    trap "kill -s 9 $VITE_SERVER_PID" EXIT
+
+    echo "Wait a little bit for the client to rebuild before opening the webpage. Else you'll get 404s"
+    # Vite takes a bit to build the client
+    sleep 8
+
     # Start server
-    cd ../server
+    cd $DOCKER_APP_PATH/server
     flask run
 elif [ "${MODE@L}" = "prod" ]; then # TODO: Integrate CJs run_prod.sh file into this portion of the script
     # Build the client
-    cd client
+    cd $DOCKER_APP_PATH/client
     npx vue-tsc --build --force && npx vite build
 
     # Start the server
-    echo hello
-    cd ../server
+    echo "Starting the server"
+    cd $DOCKER_APP_PATH/server
     flask run
+elif [ "${MODE@L}" = "dev-client" ]; then # Added so that the client can be editted in real time
+    echo "Setting up the client and server in development mode (bugs for the client will be shown with bugs for the server)"
+
+    # Start the server first
+    cd $DOCKER_APP_PATH/server
+    flask run &
+    FLASK_SERVER_PID=$!
+
+    # Kills the Flask server after the script exits
+    trap "kill -s 9 $FLASK_SERVER_PID" EXIT
+
+    # Start client second
+    cd $DOCKER_APP_PATH/client
+    # Vite is used to very quickly rebuild the client when changes are made
+    # Error messages will be shown to user
+    npx vite --port 8002 --host "0.0.0.0" --cors true
+    echo "Connect to the client at: 127.0.0.1:8002"
 fi
